---
version: "3.8"

# NOTES: 1. Test EXEC: docker -H tcp://localhost:2375 exec -it docker-socket-proxy /bin/ash
#        2. Test CURL: curl -I http://localhost:2375/tasks
#        

services:
  docker-socket-proxy:
    container_name: docker-socket-proxy
    
    # !!! THIS IS VERY DANGEROUS - ONLY DO THIS FOR TESTING !!!
    ports:
      - "2375:2375"
    
    build:
      context: ./
    
    image: mjmccans/docker-socket-proxy

    environment:
      TZ: America/Toronto
      DESCRIPTIVE_ERRORS: 0
      ALLOW_RESTARTS: 0
      AUTH: 0
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1
      DISTRIBUTION: 0
      EVENTS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 0
      NETWORKS: 0
      NODES: 0
      PING: 1
      PLUGINS: 0
      POST: 0
      DELETE: 0
      SECRETS: 0
      SERVICES: 0
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 0
      VERSION: 1
      VOLUMES: 0
      CONTAINERS_CREATE: 0
      CONTAINERS_PRUNE: 0
      CONTAINERS_RESIZE: 1
      CONTAINERS_START: 1
      CONTAINERS_UPDATE: 0
      CONTAINERS_RENAME: 0
      CONTAINERS_PAUSE: 0
      CONTAINERS_UNPAUSE: 0
      CONTAINERS_ATTACH: 0
      CONTAINERS_WAIT: 0
      CONTAINERS_EXEC: 1
      VOLUMES_CREATE: 0
      VOLUMES_PRUNE: 0
      NETWORKS_CREATE: 0
      NETWORKS_PRUNE: 0
      NETWORKS_CONNECT: 0
      NETWORKS_DISCONNECT: 0
      NETWORKS_DELETE: 0
      CONTAINERS_DELETE: 1
      IMAGES_DELETE: 0
      VOLUMES_DELETE: 0

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx.conf:/etc/nginx/nginx.conf # This is for easier testing