# Example docker-compose.yml file for Diun
#
# You can remove the environment variables that are being set to 0 (revoke), but
# the full list of options is set out below for ease of configuration. 
#

version: "3.5"

services:
  
  diun-docker-proxy:
    container_name: diun-docker-proxy
    image: mjmccans/docker-socket-proxy

    environment:
      TZ: America/Toronto
      DESCRIPTIVE_ERRORS: 0
      AUTH: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1
      CONTAINERS_ATTACH: 0
      CONTAINERS_CREATE: 0
      CONTAINERS_DELETE: 0
      CONTAINERS_KILL: 0
      CONTAINERS_PAUSE: 0
      CONTAINERS_PRUNE: 0
      CONTAINERS_RENAME: 0
      CONTAINERS_RESTART: 0
      CONTAINERS_RESIZE: 0
      CONTAINERS_START: 0
      CONTAINERS_STOP: 0
      CONTAINERS_UPDATE: 0
      CONTAINERS_UNPAUSE: 0
      CONTAINERS_WAIT: 0
      CONTAINERS_EXEC: 0
      DISTRIBUTION: 0
      EVENTS: 0
      EXEC: 0
      IMAGES: 1
      IMAGES_BUILD: 0
      IMAGES_CREATE: 0
      IMAGES_DELETE: 0
      IMAGES_PRUNE: 0
      INFO: 1
      NETWORKS: 0
      NETWORKS_CONNECT: 0
      NETWORKS_CREATE: 0
      NETWORKS_DELETE: 0
      NETWORKS_DISCONNECT: 0
      NETWORKS_PRUNE: 0
      NODES: 0
      NODES_DELETE: 0
      PING: 1
      PLUGINS: 0
      SECRETS: 0
      SERVICES: 0
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 0
      VERSION: 1
      VOLUMES: 0
      VOLUMES_CREATE: 0
      VOLUMES_DELETE: 0
      VOLUMES_PRUNE: 0

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - ./data:/data
      - ./data/diun.yml:/diun.yml:ro
  
    depends_on:
      - diun-docker-proxy
    
    environment:
      TZ: "America/Toronto"
      LOG_LEVEL: "info"
      LOG_JSON: "false"
      DIUN_WATCH_WORKERS: "20"
      DIUN_WATCH_SCHEDULE: "0 */6 * * *"
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"
      DIUN_PROVIDERS_DOCKER_ENDPOINT: tcp://diun-docker-proxy:2375 # This makes Diun use the docker-proxy as the Docker endpoint.

    restart: unless-stopped